# permissions for end users to view prs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pr-viewer-role
rules:
- apiGroups:
  - kubetempura.mercari.com
  resources:
  - prs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubetempura.mercari.com
  resources:
  - prs/status
  verbs:
  - get
